In [1]:
import pandas as pd
import os
import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification, RobertaConfig

from smart_pytorch import SMARTLoss, kl_loss, sym_kl_loss
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data as data
from torch.utils.data import (
    Dataset, 
    DataLoader, 
    RandomSampler, 
    SequentialSampler
)
import math 
from transformers.optimization import (
    AdamW, 
    get_linear_schedule_with_warmup
)
from sklearn.metrics import (
    confusion_matrix,
    matthews_corrcoef,
    accuracy_score,
    roc_curve,
    auc,
    average_precision_score,
    f1_score,
)
from scipy.special import softmax
from torch.nn import CrossEntropyLoss
from tqdm import tqdm

In [2]:
print(torch.version.cuda)
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)

11.7
1.13.1
True
True


In [3]:
# all_df = pd.read_csv('../data/financial_sen/data.csv')
all_df = pd.read_csv('..\data\FinancialPhraseBank-v1.0\Sentences_AllAgree.csv')
#all_df['Sentiment']
label = []
for index, row in all_df.iterrows():
    if row['Sentiment'] == 'negative':
        label.append(0)
    elif row['Sentiment'] == 'neutral':
        label.append(1)
    else:
        label.append(2)
        
label_df=pd.DataFrame(label)
label_df.columns = ['Class']
all_df = all_df.join(label_df)
all_df

Sentence Sentiment  Class
0     According to Gran , the company has no plans t...   neutral      1
1     For the last quarter of 2010 , Componenta 's n...  positive      2
2     In the third quarter of 2010 , net sales incre...  positive      2
3     Operating profit rose to EUR 13.1 mn from EUR ...  positive      2
4     Operating profit totalled EUR 21.1 mn , up fro...  positive      2
...                                                 ...       ...    ...
2259  Operating result for the 12-month period decre...  negative      0
2260  HELSINKI Thomson Financial - Shares in Cargote...  negative      0
2261  LONDON MarketWatch -- Share prices ended lower...  negative      0
2262  Operating profit fell to EUR 35.4 mn from EUR ...  negative      0
2263  Sales in Finland decreased by 10.5 % in Januar...  negative      0

[2264 rows x 3 columns]

In [4]:
model_name = "roberta-large"

num_labels = 3
device = torch.device("cuda")

tokenizer_name = model_name

max_seq_length = 128
train_batch_size = 8
test_batch_size = 8
warmup_ratio = 0.06
weight_decay=0.0
gradient_accumulation_steps = 1
num_train_epochs = 15
learning_rate = 1e-05
adam_epsilon = 1e-08

In [5]:
class SMARTRobertaClassificationModel(nn.Module):
    
    def __init__(self, model, weight = 0.02):
        super().__init__()
        self.model = model 
        self.weight = weight

    def forward(self, input_ids, attention_mask, labels):

        # Get initial embeddings 
        embed = self.model.roberta.embeddings(input_ids) 

        # Define eval function 
        def eval(embed):
            outputs = self.model.roberta(inputs_embeds=embed, attention_mask=attention_mask)
            pooled = outputs[0] 
            logits = self.model.classifier(pooled) 
            return logits 
        
        # Define SMART loss
        smart_loss_fn = SMARTLoss(eval_fn = eval, loss_fn = kl_loss, loss_last_fn = sym_kl_loss)
        # Compute initial (unperturbed) state 
        state = eval(embed)
        # Apply classification loss 
        loss = F.cross_entropy(state.view(-1, 3), labels.view(-1))
        # Apply smart loss 
        loss += self.weight * smart_loss_fn(embed, state)
        
        return state, loss
    
tokenizer = AutoTokenizer.from_pretrained(model_name)

config = RobertaConfig.from_pretrained(model_name, num_labels=num_labels)
model = AutoModelForSequenceClassification.from_pretrained(tokenizer_name,config=config)

model_smart = SMARTRobertaClassificationModel(model)

Some weights of the model checkpoint at roberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.bias', 'classifie

In [6]:
print('Model=\n',model_smart,'\n')

Model=
 SMARTRobertaClassificationModel(
  (model): RobertaForSequenceClassification(
    (roberta): RobertaModel(
      (embeddings): RobertaEmbeddings(
        (word_embeddings): Embedding(50265, 1024, padding_idx=1)
        (position_embeddings): Embedding(514, 1024, padding_idx=1)
        (token_type_embeddings): Embedding(1, 1024)
        (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): RobertaEncoder(
        (layer): ModuleList(
          (0): RobertaLayer(
            (attention): RobertaAttention(
              (self): RobertaSelfAttention(
                (query): Linear(in_features=1024, out_features=1024, bias=True)
                (key): Linear(in_features=1024, out_features=1024, bias=True)
                (value): Linear(in_features=1024, out_features=1024, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): RobertaSelfOutpu

In [7]:
class MyClassificationDataset(Dataset):
    
    def __init__(self, data, tokenizer):
        text, labels = data
        self.examples = tokenizer(text=text,text_pair=None,truncation=True,padding="max_length",
                                  max_length=max_seq_length,return_tensors="pt")
        self.labels = torch.tensor(labels, dtype=torch.long)
        

    def __len__(self):
        return len(self.examples["input_ids"])

    def __getitem__(self, index):
        return {key: self.examples[key][index] for key in self.examples}, self.labels[index]


all_examples = (all_df['Sentence'].astype(str).tolist(), all_df['Class'].tolist())
all_dataset = MyClassificationDataset(all_examples,tokenizer)

train_set_size = int(len(all_dataset) * 0.8)
test_set_size = len(all_dataset) - train_set_size
train_dataset, test_dataset = data.random_split(all_dataset, [train_set_size, test_set_size], generator=torch.Generator().manual_seed(0))

In [8]:
def get_inputs_dict(batch):
    inputs = {key: value.squeeze(1).to(device) for key, value in batch[0].items()}
    inputs["labels"] = batch[1].to(device)
    return inputs

train_sampler = RandomSampler(train_dataset)
train_dataloader = DataLoader(train_dataset,shuffle=True,batch_size=train_batch_size)

test_sampler = SequentialSampler(test_dataset)
test_dataloader = DataLoader(test_dataset,sampler=test_sampler, batch_size=test_batch_size)

#Extract a batch as sanity-check
# batch = get_inputs_dict(next(iter(train_dataloader)))
# input_ids = batch['input_ids'].to(device)
# attention_mask = batch['attention_mask'].to(device)
# labels = batch['labels'].to(device)

# print(batch)

In [9]:
t_total = len(train_dataloader) // gradient_accumulation_steps * num_train_epochs
optimizer_grouped_parameters = []
custom_parameter_names = set()
no_decay = ["bias", "LayerNorm.weight"]
optimizer_grouped_parameters.extend(
    [
        {
            "params": [
                p
                for n, p in model_smart.named_parameters()
                if n not in custom_parameter_names and not any(nd in n for nd in no_decay)
            ],
            "weight_decay": weight_decay,
        },
        {
            "params": [
                p
                for n, p in model_smart.named_parameters()
                if n not in custom_parameter_names and any(nd in n for nd in no_decay)
            ],
            "weight_decay": 0.0,
        },
    ]
)

warmup_steps = math.ceil(t_total * warmup_ratio)
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate, eps=adam_epsilon)
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=t_total)


C:\Users\ruoxinli3\Anaconda3\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [10]:
def compute_metrics(preds, model_outputs, labels, eval_examples=None, multi_label=True):
    assert len(preds) == len(labels)
    mismatched = labels != preds
    #wrong = [i for (i, v) in zip(eval_examples, mismatched) if v.any()]
    mcc = matthews_corrcoef(labels, preds)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='macro')
    con_m = confusion_matrix(labels, preds, labels=[0, 1, 2])
#     scores = np.array([softmax(element)[1] for element in model_outputs])
#     fpr, tpr, thresholds = roc_curve(labels, scores)
#     auroc = auc(fpr, tpr)
#     auprc = average_precision_score(labels, scores)
    return (
        {
            **{"mcc": mcc, "acc":acc, "f1": f1},
        },
        con_m
    )

def print_confusion_matrix(result):
    print('confusion matrix:')
    print('            predicted    ')
    print('          0     |     1')
    print('    ----------------------')
    print('   0 | ',format(result['tn'],'5d'),' | ',format(result['fp'],'5d'))
    print('gt -----------------------')
    print('   1 | ',format(result['fn'],'5d'),' | ',format(result['tp'],'5d'))
    print('---------------------------------------------------')


In [11]:
torch.cuda.empty_cache()

In [12]:
model_smart.to(device)

model_smart.zero_grad()
#training
for epoch in range(num_train_epochs):

    model_smart.train()
    epoch_loss = []
    
    for batch in tqdm(train_dataloader):
        batch = get_inputs_dict(batch)
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        logits, loss = model_smart(input_ids, attention_mask=attention_mask, labels=labels)
#         loss = outputs[0]
        loss.backward()
        optimizer.step()
        scheduler.step()
        model_smart.zero_grad()
        epoch_loss.append(loss.item())
        
#    SAVE
    PATH = "SMART_Roberta_large_FinancialPhraseBank/all_agree/"+str(epoch)
    torch.save(model_smart.state_dict(), PATH)
    
    
    print('epoch',epoch,'Training avg loss',np.mean(epoch_loss))

100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:38<00:00,  1.47it/s]


epoch 0 Training avg loss 0.7770353365339275


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:46<00:00,  1.44it/s]


epoch 1 Training avg loss 0.41028870109182136


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:42<00:00,  1.45it/s]


epoch 2 Training avg loss 0.2931298619056614


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:49<00:00,  1.43it/s]


epoch 3 Training avg loss 0.24699142882282027


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:50<00:00,  1.42it/s]


epoch 4 Training avg loss 0.21606794718760425


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:57<00:00,  1.40it/s]


epoch 5 Training avg loss 0.17708582991742108


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:44<00:00,  1.45it/s]


epoch 6 Training avg loss 0.1557417042264874


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:44<00:00,  1.45it/s]


epoch 7 Training avg loss 0.1520187927562242


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:29<00:00,  1.50it/s]


epoch 8 Training avg loss 0.1436526934594875


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:38<00:00,  1.47it/s]


epoch 9 Training avg loss 0.1365472677660286


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:47<00:00,  1.44it/s]


epoch 10 Training avg loss 0.12917742550051692


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [06:22<00:00,  1.53it/s]


epoch 11 Training avg loss 0.12701597296982073


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [05:59<00:00,  1.63it/s]


epoch 12 Training avg loss 0.12081201061363626


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [05:59<00:00,  1.63it/s]


epoch 13 Training avg loss 0.11949191824483295


100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [05:58<00:00,  1.63it/s]


epoch 14 Training avg loss 0.11971130293990986


In [12]:
model_smart.to(device)

for epoch in range(num_train_epochs):
    
    #evaluate model with test_df at the end of the epoch.
    eval_loss = 0.0
    nb_eval_steps = 0
    n_batches = len(test_dataloader)
    preds = np.empty((len(test_dataset), num_labels))
    out_label_ids = np.empty((len(test_dataset)))
    
    PATH = "SMART_Roberta_large_FinancialPhraseBank/all_agree/"+str(epoch)
    model_smart.load_state_dict(torch.load(PATH))
    model_smart.eval()
    
    for i,test_batch in enumerate(test_dataloader):
#         with torch.no_grad():
        test_batch = get_inputs_dict(test_batch)
        input_ids = test_batch['input_ids'].to(device)
        attention_mask = test_batch['attention_mask'].to(device)
        labels = test_batch['labels'].to(device)
        logits, tmp_eval_loss = model_smart(input_ids, attention_mask=attention_mask, labels=labels)
    #             tmp_eval_loss, logits = outputs[:2]
        eval_loss += tmp_eval_loss.item()
            
        nb_eval_steps += 1
        start_index = test_batch_size * i
        end_index = start_index + test_batch_size if i != (n_batches - 1) else len(test_dataset)
#         print(logits)
        preds[start_index:end_index] = logits.detach().cpu().numpy()
        out_label_ids[start_index:end_index] = test_batch["labels"].detach().cpu().numpy()
        
    eval_loss = eval_loss / nb_eval_steps
    model_outputs = preds
    preds = np.argmax(preds, axis=1)
    result, con_m = compute_metrics(preds, model_outputs, out_label_ids)
    
    #print('epoch',epoch,'Training avg loss',np.mean(epoch_loss))
    print('epoch',epoch,'Testing  avg loss',eval_loss)
    print(result)
    print(con_m)
    print('---------------------------------------------------\n')

epoch 0 Testing  avg loss 0.23822243756761677
{'mcc': 0.8736551473606629, 'acc': 0.9315673289183223, 'f1': 0.9029083779277642}
[[ 51   4   9]
 [  0 274   1]
 [  3  14  97]]
---------------------------------------------------

epoch 1 Testing  avg loss 0.034165700581006445
{'mcc': 0.9839327829616051, 'acc': 0.9911699779249448, 'f1': 0.9897465738306881}
[[ 64   0   0]
 [  0 273   2]
 [  1   1 112]]
---------------------------------------------------

epoch 2 Testing  avg loss 0.046738144866060136
{'mcc': 0.9680263946915314, 'acc': 0.9823399558498896, 'f1': 0.9732323594778612}
[[ 59   0   5]
 [  0 273   2]
 [  0   1 113]]
---------------------------------------------------

epoch 3 Testing  avg loss 0.09813802539607869
{'mcc': 0.943918755799384, 'acc': 0.9690949227373068, 'f1': 0.9565344265132351}
[[ 58   2   4]
 [  0 270   5]
 [  2   1 111]]
---------------------------------------------------

epoch 4 Testing  avg loss 0.050688672632085194
{'mcc': 0.9639767578603361, 'acc': 0.98013245033

In [12]:
df_sample =  pd.read_csv("../data/seeking_alpha_cleaned.csv")
# df_sample
new_labels=np.zeros(234)

sample_examples = (df_sample['summary'].astype(str).tolist(),new_labels)
sample_dataset = MyClassificationDataset(sample_examples,tokenizer)

sample_dataloader = DataLoader(sample_dataset,shuffle=False,batch_size=test_batch_size)

print(sample_dataloader)

In [13]:
import datasets
sample_data = datasets.load_dataset('zeroshot/twitter-financial-news-sentiment', split='validation')

new_label = []
for s in sample_data:
    if s['label'] == 1:
#         print('f')
        new_label.append(2)
    elif s['label']==2:
        new_label.append(1)
    else:
        new_label.append(0)
sample_examples = (sample_data['text'], new_label)
sample_dataset = MyClassificationDataset(sample_examples,tokenizer)
sample_dataloader = DataLoader(sample_dataset,shuffle=False,batch_size=test_batch_size)

Using custom data configuration zeroshot--twitter-financial-news-sentiment-ccca0f3c622c5b67
Found cached dataset csv (C:/Users/ruoxinli3/.cache/huggingface/datasets/zeroshot___csv/zeroshot--twitter-financial-news-sentiment-ccca0f3c622c5b67/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317)


In [14]:
model_smart.to(device)
pred_final = []
for epoch in range(8,9):
    
    #evaluate model with test_df at the end of the epoch.
    eval_loss = 0.0
    nb_eval_steps = 0
    n_batches = len(sample_dataloader)
    preds = np.empty((len(sample_dataset), num_labels))
    out_label_ids = np.empty((len(sample_dataset)))
    
    PATH = "SMART_Roberta_large_FinancialPhraseBank/all_agree/"+str(epoch)
    model_smart.load_state_dict(torch.load(PATH))
    model_smart.eval()
    
    for i,test_batch in enumerate(sample_dataloader):
#         with torch.no_grad():
        test_batch = get_inputs_dict(test_batch)
        input_ids = test_batch['input_ids'].to(device)
        attention_mask = test_batch['attention_mask'].to(device)
        labels = test_batch['labels'].to(device)
        logits, tmp_eval_loss = model_smart(input_ids, attention_mask=attention_mask, labels=labels)
    #             tmp_eval_loss, logits = outputs[:2]
        eval_loss += tmp_eval_loss.item()
            
        nb_eval_steps += 1
        start_index = test_batch_size * i
        end_index = start_index + test_batch_size if i != (n_batches - 1) else len(sample_dataset)
#         print(logits)
        preds[start_index:end_index] = logits.detach().cpu().numpy()
        out_label_ids[start_index:end_index] = test_batch["labels"].detach().cpu().numpy()
        
    eval_loss = eval_loss / nb_eval_steps
    model_outputs = preds
    preds = np.argmax(preds, axis=1)
    result, con_m = compute_metrics(preds, model_outputs, out_label_ids)
    if epoch == 8:
        pred_final = preds 
    
    #print('epoch',epoch,'Training avg loss',np.mean(epoch_loss))
    print('epoch',epoch,'Testing  avg loss',eval_loss)
    print(result)
    print(con_m)
    print('---------------------------------------------------\n')

epoch 8 Testing  avg loss 2.849648731946945
{'mcc': 0.0, 'acc': 0.4658119658119658, 'f1': 0.21185617103984447}
[[109  16 109]
 [  0   0   0]
 [  0   0   0]]
---------------------------------------------------



In [18]:
pred_final_df=pd.DataFrame(preds)
pred_final_df.columns = ['pred_sen']
df_sample = df_sample.join(pred_final_df)
df_sample

author                       date  ticker  \
0    Daniel Jones  2023-03-13T10:45:44-04:00     DJI   
1    Daniel Jones  2023-03-13T10:45:44-04:00     NDX   
2    Daniel Jones  2023-03-13T10:45:44-04:00   SP500   
3    Daniel Jones  2023-03-13T10:45:44-04:00     SPX   
4    Daniel Jones  2023-03-11T04:53:53-05:00     BMI   
..            ...                        ...     ...   
229  Hoya Capital  2023-02-27T08:10:00-05:00     MMM   
230  Hoya Capital  2023-02-27T07:30:00-05:00     ENB   
231  Hoya Capital  2023-02-27T07:30:00-05:00  ENB:CA   
232  Hoya Capital  2023-02-26T08:00:00-05:00    QRMI   
233  Hoya Capital  2023-02-26T08:00:00-05:00    XRMI   

                                               summary  pred_sen  
0    Markets have been volatile, initially starting...         0  
1    Markets have been volatile, initially starting...         0  
2    Markets have been volatile, initially starting...         0  
3    Markets have been volatile, initially starting...         0  
4    Badger Meter continues to grow, and most of it...         2  
..                                                 ...       ...  
229  3M is now trading at a very low valuation and ...         0  
230  Enbridge's utilization levels remain high, wit...         2  
231  Enbridge's utilization levels remain high, wit...         2  
232  The Global X S&P 500 Risk Managed Income ETF i...         1  
233  The Global X S&P 500 Risk Managed Income ETF i...         1  

[234 rows x 5 columns]

In [20]:
df_sample.to_csv("../data/seeking_alpha_pred.csv",index=False)